# Generated by Django 3.2.16 on 2024-07-20 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0002_birthday_autor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='birthday',
            old_name='autor',
            new_name='author',
        ),
    ]
